export const ADD_PAYMENT = "ADD_PAYMENT";
export const RETRIEVE_PAYMENTS = "RETRIEVE_PAYMENTS";
export const RETRIEVE_VIEWALL_PAYMENTS ="RETRIEVE_VIEWALL_PAYMENTS";
export const RETRIEVE_CALCULATETOTAL_PAYMENT="RETRIEVE_CALCULATETOTAL_PAYMENT";

export const UPDATE_PAYMENT = "UPDATE_PAYMENT";
export const DELETE_PAYMENT = "DELETE_PAYMENT";